server:
  port: 8080
management:
  info:
    build:
      enabled: true
    git:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  data:
    mongodb:
      uri: mongodb://mongodb:27017/notedb